# Generated by Django 2.1.5 on 2019-01-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(blank=True, max_length=50)),
                ('secret', models.CharField(blank=True, max_length=50)),
                ('server', models.CharField(blank=True, max_length=50)),
                ('farm', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('owner_name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flickr.Flickrgroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='photos',
            name='group',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
