# Generated by Django 2.1.5 on 2019-01-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0005_auto_20190112_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrgroup',
            name='profile',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='flickr.Profile'),
            preserve_default=False,
        ),
    ]
