# Generated by Django 2.1.5 on 2019-01-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0006_flickrgroup_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='flickrgroup',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(to='flickr.Flickrgroup'),
        ),
    ]
